#!/bin/ksh

#-----------------------------------------------------------------------------
#SBATCH --job-name=run_ERISWILL
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --time=01:00:00
#SBATCH --account=bb1262
#SBATCH --output=%j.out
#SBATCH --error=%j.err
#SBATCH --mem=0


#-----------------------------------------------------------------------------
# Environment:
#-----------------------------------------------------------------------------
source /etc/profile
module load arm-forge/22.1-gcc-11.2.0



# limit stacksize ... adjust to your programs need
ulimit -s 204800
ulimit -c 0

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/sw/spack-levante/netcdf-fortran-4.5.3-k6xq5g/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/sw/spack-levante/netcdf-c-4.8.1-2k3cmu/lib

export OMP_NUM_THREADS=2
export OMP_SCHEDULE=dynamic,1
export OMP_DYNAMIC="false"
export OMP_STACKSIZE=200M
# 
export SLURM_DIST_PLANESIZE="8"
export KMP_AFFINITY="granularity=fine,scatter"
export KMP_LIBRARY="turnaround"
export KMP_KMP_SETTINGS="1"
export OMP_WAIT_POLICY="active"
export KMP_WARNINGS="0"
export MKL_ENABLE_INSTRUCTIONS="AVX2"
export MKL_DEBUG_CPU_TYPE="5"
export KMP_LIBRARY="turnaround"
export KMP_AFFINITY="granularity=fine,scatter"
export OMPI_MCA_osc="pt2pt"
export OMPI_MCA_pml="ucx"
export OMPI_MCA_btl="self"
export OMPI_MCA_coll="^hcoll,ml"
export OMPI_MCA_io="romio321"
export UCX_TLS="self,sm,dc_mlx5,dc_x"
export UCX_UNIFIED_MODE="y"

# --------------------------
# number of cpus 
# --------------------------
NTASKS=128
rm YU*

# --------------------------
# DOMAIN SIZE
# --------------------------

#CASE='122x112'
#CASE='42x32'
CASE="12x12"

if [[ $CASE = '12x12' ]]; then
   NTASKS=16
fi
echo "CASE: " $CASE
cp -p INPUT_DYN_${CASE} INPUT_DYN
cp -p INPUT_IO_${CASE} INPUT_IO
cp -p INPUT_ORG_${CASE} INPUT_ORG


# ---------------------------
# how to start the specs model
# ---------------------------
#echo ${SLURM_JOB_NUM_NODES:=1}
#echo ${SLURM_JOB_CPUS_PER_NODE%%\(*} 
no_of_nodes=${SLURM_JOB_NUM_NODES:=1}

mpi_procs_pernode=$((${SLURM_JOB_CPUS_PER_NODE%%\(*} / 1 / $OMP_NUM_THREADS))
num_tasks=${NTASKS}
# num_tasks=$((no_of_nodes * mpi_procs_pernode))
# echo ${SLURM_JOB_NUM_NODES:-1}
# echo $((no_of_nodes * mpi_procs_pernode))
# echo ${mpi_procs_pernode}
# echo ${num_task}
START="srun -l --kill-on-bad-exit=1 --nodes=${SLURM_JOB_NUM_NODES:-1} --hint=nomultithread --distribution=block:cyclic:block --cpu-bind=v,cores --ntasks=${num_tasks} --ntasks-per-node=${mpi_procs_pernode} --cpus-per-task=1"

MODEL="${PWD}/psbm_fd4_levante"


date
ddt --connect ${START} ${MODEL} # > out.txt 2>&1
date



